Packages.props, src/KissTnc/TncInterface.cs, test/KissTncUnitTests/TNCInterfaceUnitTests.cs
Adds a new static analyzer in the form of [IDisposableAnalyzers](https://www.nuget.org/packages/IDisposableAnalyzers/). The new analyzer immediately caught a violation where the project was not properly disposing a system-level resource, so this change also cleans that up. This is part of #27.
* Add IDisposableAnalyzers to the common packages imported by all projects
* Fix violations of the new analyzer
* Build passes locally
=> Add IDisposableAnalyzers and fix violations

.github/workflows/build.yml, .github/workflows/markdown.yml
Having recently seen examples of runaway Actions that hang, I'm adding a lower timeout. Default timeout is 360 minutes, which is much, much too high. This changes it to 5 minutes.
This provides faster feedback on failures and feedback at all if we hugely balloon build time. Although we don't have to pay for Actions minutes as a public repository, we should not expect our Actions times to explode by a factor of 5 with no warning.
* Added timeout to both workflow files
* Modified markdown lint workflow to ensure the Action always runs if any workflow files are changed
* Checked that there are no runs that take even 30% of that time
* Actions will run with new time limits as part of this PR
=> Decreased timeout on Actions to 5 minutes

Directory.Build.props, README.md
This changes the behavior of the build to allow warnings without failing during local development. That means things like "elements should be documented" will not fail the build on a developer's machine and will allow testing and running to continue.
Warnings will still be treated as errors for release builds as executed by the GitHub Actions CI build. Individual developers can replicate the behavior by specifying the build configuration: `dotnet build --configuration Release`.
This comes from a @lugolven recommendation here: https://github.com/CBielstein/APRSsharp/pull/19#discussion_r445873420
* Wrap warnings as errors properties in a conditional property group
* Updated readme
* Took the chance to specify `MSBuildTreatWarningsAsErrors` as recommended by @lugolven
* Wrote a method that …
=> Warnings as errors only in release build

test/AprsParserUnitTests/PacketUnitTests.cs, test/AprsParserUnitTests/PositionUnitTests.cs, test/AprsParserUnitTests/TimestampUnitTests.cs
Use `Assert.Throws` for tests expecting an exception
Changed try..catch blocks in tests to Assert.Throws<>
Confirmed Build succeeded and tests passed
=> Use `Assert.Throws` for tests expecting an exception

src/KissTnc/FrameReceivedEventArgs.cs, src/KissTnc/KISSProtocolValues.cs, src/KissTnc/KissTnc.csproj, src/KissTnc/TncInterface.cs, test/KissTncUnitTests/KissTncUnitTests.csproj, test/KissTncUnitTests/TNCInterfaceUnitTests.cs
This is the first of several changes to incrementally enable FxCopAnalyzers in this repository. FxCopAnalyzers allows us to increase code quality of existing code and ensure code quality of new code. Since there are many FxCop violations in this repository, I'm breaking up the large change in to several smaller changes based on project. I will add FxCopAnalyzers to our project Packages.props once the package is enabled everywhere.
This is part of #27 
* Adds FxCopAnalyzers to KissTnc and KissTncUnitTests projects
* Fixes FxCop violations in those projects
* `dotnet build -c Release` is successful (no violations) on my machine
* Tests are running successfully
=> Enable FxCop Analyzers in KissTnc directories

.github/CODEOWNERS
[Code owners](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) is a GitHub feature to require approval from specific individuals before PRs can be merged in to the main branch. Code owners are also automatically requested for reviews on PRs, which should help us ensure each PR adds each other in case we forget.
This PR adds an initial CODEOWNERS file which requires approval from either @CBielstein or @eddywine to merge code in to this repository.
* Add `CODEOWNERS` file as described above.
* Will be validated after submitting this PR (new PRs should automatically add code owners, etc.)
=> Add an initial codeowners file

src/AprsParser/Packet.cs, src/AprsParser/Timestamp.cs, src/KissTnc/TncInterface.cs
The codebase now has a few places where methods are overloaded when optional parameters could be used instead. This adds to the call stack and bloats code. This PR removes a few unnecessary overloads to aim for reducing code bloat.
This resolves #66.
* Combine overloaded methods using optional parameters
* Removed a couple of unused constructor overloads
* Build and tests passing
=> Swap overload methods for optional parameters

.github/workflows/build.yml, Directory.Build.props, README.md, src/APRSsharp/APRSsharp.csproj, src/APRSsharp/Program.cs, test/AprsParserUnitTests/AprsParserUnitTests.csproj, test/KissTncUnitTests/KissTncUnitTests.csproj
This PR moves to .NET 6 and C# 10 to enable use of new runtime enhancements and language features. This closes #84.
* Changes application projects to target .NET 6.0
* Updates language version to C# 10
* Fixes warnings around newly nullable code in .NET 6.0
* Updates .NET SDK version in GitHub Action
* Updates documentation
* `dotnet run` succeeds
* Build and tests pass
* Publish and run succeeds
=> Move to .NET 6 and C# 10

src/AprsParser/RegexStrings.cs
C#10 introduced the ability for constant string interpolation. This means one constant string can be constructed from other constant strings and performance gains can be realized.
Currently, our regex patterns use string interpolation to include sub-patterns and promote reuse. However, since we haven't been on C#10 until recently, some of these strings could not be constant values.
This PR takes advantage of that and makes the remaining regex patterns constant across the board. This closes #81.
* Disable the static analysis suppression now that we're on C#10
* Update string definitions to const
* Build and tests pass
=> Use constant string interpolation

src/APRSsharp/Program.cs, src/AprsISLibrary/AprsIsConnection.cs
In order to get customized server-side filtering, we need to expose the ability to customize the filter argument when logging in to an APRS-IS server. This PR addresses that by making filter an optional parameter on AprsIsConnection and allowing input in the AprsSharp CLI.
Note, this is a first part of #63, but does not complete all of it.
* Expose the filter argument in `AprsIsConnection.Receive(string?, string?, string?)`
* Add `Console.ReadLine()` input to take the filter on the command line
* Build and tests pass
* Manually validated by filtering to different locations and seeing different packets. See attached screenshot. Coordinates are Seattle's Space Needle, observe gridsquare CN87 in position reports
=> Enable custom filter in AprsIsConnection and AprsSharp CLI

src/APRSsharp/Program.cs, src/AprsISLibrary/AprsIsConnection.cs
As discussed in #100, a bug was introduced in #98 wherein the default filter input (CLI pushing enter without entering a value) resulted in no packets sent by the server.
This was due to `Console.ReadLine()` returning an empty string when nothing was entered rather than `null` as was incorrectly expected.
This change addresses this by moving all "default parameters" logic to the CLI client and out of the server logic. This is consistent with a separation of concerns between the client handling user input and the server library handling server interaction.
This also allows sidestepping the issue of differentiating between a user not supplying a filter (thus wanting the default) or a user supplying explicitly NO filter (not wanting a default or anything else, e.g. the full feed for a …
=> Move default parameters to CLI instead of server connection

src/APRSsharp/Program.cs, src/AprsIsConnection/AprsIsConnection.cs, src/AprsIsConnection/AprsIsConnection.csproj, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
This PR adds a new event that is raised when `AprsIsConnection` receives and successfully decodes a packet. This is different than the existing event that is raised on every single TCP message received from the server. This event fully decodes a packet and passes it to the event handler.
The goal of this change is to offload work from the client by reducing the kind of code the client will have to duplicate. Instead of all clients writing the packet decode call, this can be handled directly by the `AprsIsConnection`, reducing requirements on the client to simply handling the packet that is received.
This resolves #80.
* Add `ReceivedPacket` event to `ApsIsConnection` and decode packets when there is a subscriber to the event.
* Add testing
* Updated the yield logic on the receive task to …
=> Add ReceivedPacket event to AprsIsConnection

src/AprsParser/InfoField/PositionInfo.cs, src/AprsParser/RegexStrings.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs, test/AprsParserUnitTests/InfoField/PositionInfoUnitTests.cs
The last of the remaining scenarios in the `PositionInfo` code is decoding `PacketType.PositionWithoutTimestampWithMessaging`. This PR resolves that issue.
Along with #109, this should allow APRS# to encode and decode any complete weather reports and position packets.
This was a pretty straightforward change as most of the code was already implemented. I added some encode and decode tests (encode of this already worked, only decode needed fixing, but more tests are always good!).
All that was left was to merge the "without timestamp" cases of position decode and set messaging support based on the packet type. This pattern follows the decode of the "with timestamp" types just below in the same file.
This will resolve #92.
* Added both encode and decode test cases for …
=> Implement decode on PositionWithoutTimestampWithMessaging

.github/workflows/release.yml, Directory.Build.props, README.md, src/AprsIsConnection/AprsIsConnection.csproj, src/AprsParser/AprsParser.csproj
This PR adds the relevant code, documentation, and a new GitHub Action to track two new nuget packages:
* AprsSharp.AprsParser
* AprsSharp.AprsIsClient (our AprsIsConnection library, to be renamed in the future)
This will allow reuse of this code by other code bases and users.
For now, the packages will all have the same version and will change together. They will also be versioned 0.x.y (version 0) until a future date where the public classes and methods can be stabilized.
* Add relevant fields for nuget packages to AprsParser and AprsIsConnection
* Add new workflow for publishing nuget packages when a GitHub release is created
* Add documentation
* Inspected locally created nuget packages with https://nuget.info to ensure dependencies and properties are correct
* Used local nuget …
=> Create AprsSharp.AprsParser and AprsSharp.AprsIsClient Nuget Packages

.github/workflows/release.yml
#111 was missing the lines to set the environment variable for the nuget API key. This was caught when creating a release in GitHub. This PR addresses that by properly setting the environment variable based on the GitHub repository secret.
* Set environment variable in release workflow based on corresponding GitHub repo secret
* Will be validated by running a release
=> Fix for environment variable in release Actions workflow

.github/workflows/release.yml
Specify public nuget source for releasing nuget packages.
Follows up on #111, #112, and #113.
* Adds `--source` flag to `dotnet nuget push` commands.
* Will create a release once this is merged to verify.
=> Specify public nuget source for releasing packages

src/AprsIsConnection/AprsIsConnection.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
Currently, the AprsSharp version sent to the APRS-IS server is hard-coded in to the connection logic. However, the version used for publishing packages is saved in the package properties (Directory.Build.props sets it across all projects/assemblies).
This changes our code to use reflection to get the assembly version of the AprsIsConnection being used to communicate to the server. Thus eliminating one place to remember to change the version on each release. It should now only be required to update the build properties in the code on each version.
* Use reflection to reference assembly version for identifying software version to APRS-IS servers
* Updated tests
* Ran AprsSharp CLI and noted the version had updated to the full semver "0.1.0" string
* Temporarily updated just the …
=> Reuse Package Version for APRS-IS Login

src/AprsIsConnection/AprsIsConnection.cs, src/AprsIsConnection/ConnectionState.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
This switches from a simple "logged in" Boolean flag to tracking state across the full life of the `AprsIsConnection` object. It also adds an event which can be subscribed to for notifications of when that status changes.
This is especially useful for clients who may wish to know when a connection has been achieved, a login complete, or some error has lead to a disconnect and a new connection is required.
* Remove `AprsIsConnection.LoggedIn` in favor of `AprsIsConnection.State`
* Introduce `ConnectionState` enum for various states an APRS-IS connection can hold
* Updates and adds tests for validation
* Updated tests away from `AprsIsConnection.LoggedIn` to `AprsIsConnection.State`
* Added new tests for disconnected events
* All tests passing
=> Add AprsIsConnection.State and State Change Events

src/APRSsharp/APRSsharp.csproj, src/APRSsharp/Program.cs, src/AprsIsConnection/AprsIsConnection.cs, src/AprsIsConnection/AprsIsConnection.csproj, test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.csproj, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
This adds logging verbosity support to APRS#. A new command line argument accepts the ability to change the level of logged events, which allows users to change how much logging they see.
This also sets the default level to exclude packet decode failures, which cleans up output here and allows cleaning up logging when using the nuget package.
Resolves #118.
* Switch AprsIsConnection logging from `Console.Error` to `ILogger` and relevant methods
* Pass in an `ILogger` to use for logging events
* Add a command line parameter to set the level of logging
* Validated by running locally with various verbosity levels set and observing the output
=> Add log "verbosity" argument and functionality

src/APRSsharp/Program.cs, src/AprsIsConnection/AprsIsConnection.cs, test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
As described in #122, the APRS-IS servers stop sending data after 48 hours, causing any connected client to stop receiving new packets.
This change adds an event that re-sends the login message every 6 hours to maintain connection and reset the 48hour timeout counter.
This resolves #122.
This uses `System.Threading.Timer` instead of `System.Timers.Timer` to allow multi-threaded use of the underlying `TcpClient` so that receiving is not interrupted.
* Add a timer event triggering every 6 hours to message the APRS-IS server
* This makes `AprsIsConnection` disposable, so the required changes were implemented for that as well
* Build and tests pass
* Ran locally with a shorter timeframe and verified that APRS-IS servers reset their timeout counter (via APRS-IS server status page) each time a …
=> Maintain Connection with APRS-IS Server

Directory.Build.props
Adding additional package properties to add information to the package Nuget.org listings.
These come from the [Microsoft package authoring best practices](https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices).
* Add project URL referencing this repo
* Add repository URL referencing this repo
* Add repository type as git
* Add license type as MIT
* Copyright message
* Build and pack work locally
* Used [Nuget Package Explorer](https://nuget.info) to inspect package after local build and observed new properties as expected
=> Added additional nuget package properties

src/APRSsharp/Program.cs, src/AprsIsConnection/AprsIsConnection.cs, src/AprsIsConnection/ITcpConnection.cs, src/AprsIsConnection/TcpConnection.cs, test/AprsIsConnectionUnitTests/DisposeUnitTests.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
Currently, as unit tests require the ability to inject an `ITcpConnection`, `AprsIsConnection` has a single constructor which requires specifying an `ITcpConnection`.
However, most clients will not need or want to specify their own `ITcpConnection`, so this is overly cumbersome. Instead, this PR changes the incoming `ITcpConnection` to be optional.
To handle ambiguity around if the `ITcpConnection` should be disposed, we follow the pattern laid out by Microsoft's own [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0), which [allows injection of an `HttpMessageHandler` and specifying whether the HttpClient or the caller should dispose the handler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.-ctor?view=net-6.0#system-n …
=> Manage creation and disposal of `ITcpConnection` in `AprsIsConnection`

src/AprsIsConnection/AprsIsConnection.cs, src/AprsIsConnection/ITcpConnection.cs, src/AprsIsConnection/TcpConnection.cs, test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.cs, test/AprsIsConnectionUnitTests/ReceiveUnitTests.cs
The current strategy for handling TCP connection interruptions is to rely on an exception on connection disruption. However, if a remote server respectfully closes the connection (as opposed to the connection being interrupted), no exception is generated and the read methods will continue to return empty strings, causing our code to never detect the disconnect and receive empty messages without stopping.
This change pipes through the connection state of the underlying `TcpClient` to check connection on each cycle of the receive loop. This allows the code to detect a disconnection by the server and set the state of the `AprsIsConnection` to disconnected to match.
* Pipe through `TcpClient.Connected` check to `ITcpConnection` and `TcpConnection`
* Add a check against …
=> Detect TCP server disconnection

src/AprsParser/RegexStrings.cs, test/AprsParserUnitTests/PositionUnitTests.cs
The regular expression for a position with symbols had a typo specifying latitude in north and west instead of north and south. This PR corrects that typo and adds a test to validate the change.
* Fix typo in regex
* Add test
* Add test in south and east lat/long to ensure all directions are parsing correctly
* All tests passing
=> Correct Typo in Position Regex

src/AprsIsClient/AprsIsClient.cs, test/AprsIsClientUnitTests/AprsIsClientUnitTests.cs, test/AprsIsClientUnitTests/ReceiveUnitTests.cs
As described in #120, a rotating address is often used to connect to an APRS-IS server; however, the actual connected server is not known to the user.
This change adds parsing to the AprsIsClient class to obtain the connected server and expose it as a property of the class.
- Add nullable public property, ConnectedServer, to AprsIsClient
- Add parsing logic via private method to obtain the server name from the connected server's login response and assign to ConnectedServer.  If server name cannot be determined, the property value is set to null.
- Private method also logs server name
- Build passes
- Created and passed unit tests
- Ran locally at LogInformation visibility level to confirm server name is captured in property
=> Add ConnectedServer Property to AprsIsClient

src/APRSsharp/Program.cs, src/AprsParser/InfoField/WeatherInfo.cs, test/AprsParserUnitTests/InfoField/WeatherInfoUnitTests.cs
Trims the encoded weather measurements from the `WeatherInfo` info field object.  Places the remaining "user" comment into the `Comment` property of the `WeatherInfo` object. 
#105 
*Add `Comment` property to `WeatherInfo` class.  `PositionInfo` base class will still hold the untrimmed comment.
*Add logic in `WeatherInfo` to determine the consecutive portion of the comment which contains weather measurement data and strips that out of the comment.  Weather measurements inside the comment will remain in the user comment and be evaluated as measurements.
*Update `PrintPacket` to display weather user comment
*Modify and create unit tests
*Build passes
*Passed unit tests for encode/decode
*Ran with live data and confirmed user comment captured as desired
=> WeatherInfo parses out comment text 

.github/workflows/build.yml, .github/workflows/markdown.yml, .github/workflows/release.yml
Resolves #139 by updating actions versions of actions using older node runtime versions.
* Updates actions/checkout from v2 to v3
* Updates actions/setup-dotnet from v1 to v3
* Validated as part of this PR
=> Update actions versions for node16 runtime

src/AprsParser/InfoField/StatusInfo.cs, src/AprsParser/Position.cs, src/AprsParser/RegexStrings.cs, test/AprsParserUnitTests/InfoField/StatusInfoUnitTests.cs
Implements encode and decode of Status info fields without a position.
Resolves #88.
* Implements encode and decode of non-maidenhead status reports
* Adds required helpers and regex strings
* Expands tests for new scenarios
* Tests and lint are successful
* Able to run APRSsharp.exe and view status reports without position both with and without timestamp using `-f t/s`
=> Status no maiden

src/AprsParser/Packet.cs, test/AprsParserUnitTests/InfoField/MaidenheadBeaconInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/MessageInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/PositionInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/StatusInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/WeatherInfoUnitTests.cs
Renames `string Packet.Encode()` to explicit `string Packet.EncodeTnc2()` to make way for upcoming AX.25 byte encoding work. AX.25 requires encode to bytes, but TNC2 can encode to string without losing data. Separating the implementations now allows their logic to evolve separately as we go forward.
This is the first PR for #145
* Rename `Packet.Encode` to `Packet.EncodeTnc2`
* Update references in tests
* Linting and tests pass
=> Rename `Packet.Encode` to `Packet.EncodeTnc2`

src/APRSsharp/Program.cs
`WeatherInfo` packets are being displayed with inconsistent indentation. Basic information is correctly indented to 4 spaces, but the remaining weather info is not indented at all. This change fixes that.
* Adds indentation to `WeatherInfo` display code in APRSsharp CLI
* Manual testing shows correct indentation
=> Correct WeatherInfo display indentation

src/APRSsharp/APRSsharp.csproj
There are a few nuget packages that are not referenced or used in the code, though some of the dependencies of the dependencies are used. This removes the unused packages and adds an explicit dependency on what is required.
* Remove package reference to unused nuget packages
* Adds an explicit reference to the correct dependency
* Tests pass
* Linting passes
* Manually running APRSsharp CLI works
=> Remove package references to unused nuget packages

src/APRSsharp/Program.cs, src/AprsParser/InfoField/InfoField.cs, src/AprsParser/InfoField/UnsupportedInfo.cs, test/AprsParserUnitTests/InfoField/UnsupportedInfoUnitTests.cs
Introduces `UnsupportedInfo` to allow for displaying partial decode and raw (undecoded) info field from packets with an info field that is not supported by APRS#.
Display of these packets is disabled by default in APRSsharp.exe but can be enabled with the new `--display-unsupported` flag.
`UnsupportedInfo` cannot be used for encoding in an effort to reduce using APRS# to send non-standard packets that might clutter the network.
Resolves #148.
* Add `UnsupportedInfo` info field
* Use it for any info field that is not known or supported during packet decode
* Add display of these new types to APRS# CLI app behind optional `--display-unsupported` flag
* Adds new tests
* Manually tested against APRSIS to display or not display based on flag in CLI app
* Added new tests
=> Add new `UnsupportedInfo` info field type to display unsupported packet types

src/APRSsharp/Program.cs, src/APRSsharp/Properties/launchSettings.json, src/AprsParser/Packet.cs, src/AprsParser/RegexStrings.cs, test/AprsParserUnitTests/InfoField/MessageInfoUnitTests.cs, test/AprsParserUnitTests/PacketAx25UnitTests.cs
Implements AX.25 TNC send and receive via TCP IP. Done as a lump to allow testing with real hardware and direwolf for a TCP connected TNC.
Resolves #144 
Resolves #145
Resolves #147 
* Switches packet decode to be bytes instead of string
* Implements AX.25 encode
* Implements AX.25 decode
* Adds AX.25 encode-decode test
* Adds ability to send packet via TCP TNC in APRSsharp.exe
* Tests pass
* Manual validation with hardware and direwolf
=> Implement AX.25 TNC Send and Receive

.github/workflows/release.yml, Directory.Build.props, src/Shared/Shared.csproj, test/AprsIsClientUnitTests/ReceiveUnitTests.cs
The Shared library needs to be published as both `AprsSharp.AprsIsClient` and `AprsSharp.KissTnc` depend on it. Nuget restore step will incorrectly restore a package called `Shared`. This PR publishes `AprsSharp.Shared` so that the shared code can be restored and used.
Version is also bumped to 0.3.1.
* Declare `AprsSharp.Shared` as a new package
* Add pack and publish steps
* Bump version to 0.3.1
* Build succeeds
* Will release after merge and test restore in a different project
=> Publish Shared package

.github/workflows/build.yml, .github/workflows/release.yml, README.md, src/APRSsharp/APRSsharp.csproj, src/AprsIsClient/AprsIsClient.csproj, test/AprsIsClientUnitTests/AprsIsClientUnitTests.csproj, test/AprsParserUnitTests/AprsParserUnitTests.csproj, test/KissTncUnitTests/KissTncUnitTests.csproj
Upgrades build and validation to use .NET8.0, which is the latest LTS version. .NET6.0 is out of support now.
* Changes target frameworks to .NET8.0
* Changes GitHub Actions to install .NET8.0
* Handles breaking changes:
* Updates MSTest dependency to fix test discovery failure in .NET8
* Specifies exclude commit hash in version as per https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link
* Build succeeds on local machine with .NET8
* All tests pass on local machine with .NET8
* GitHub Actions will validate in the cloud as part of this PR
=> Change build and validation to .NET8

README.md, src/APRSsharp/APRSsharp.csproj
Updates runtime targets for CLI app. Now targets x64 instead of x86 (as Microsoft winds down support for x86 hardware) and adds Linux x64 now that I've validated on that platform.
* Changes runtime build targets to 64-bit of each linux and windows
* Updates readme on publish location
* Works on My Machine(TM)
=> Update Runtime Builds for CLI

src/Shared/TcpConnection.cs
#153 resulted resulted in a regression with APRS-IS. That was reported by #161 (thanks @ShawnStoddard ) . The issue is described in comments there but, briefly, the change in how TCP messages were being sent meant the newline characters expected by APRS-IS servers were no longer being appended to messages. This PR resolves #161 by adding explicit newline bytes to the sent message.
Manual testing confirms the fix on APRS-IS. However, due to the layers of abstraction, this is a bit difficult to test in an automated fashion. For now, we'll just rely on end-to-end manual testing.
* Removes unnecessary newline arg as we aren't using strings and lines in TCP connections anymore
* Manually sends the newline bytes after each message
* Manually confirmed that I didn't receive from APRS-IS before …
=> Resolve APRSIS Login Issue

src/APRSsharp/Program.cs, src/AprsIsClient/AprsIsClient.cs
As reported in #162 by @ShawnStoddard (thanks!), the default filter string in the CLI includes the word `filter`, which is later appended by the AprsIsClient. This PR removes that additional/unnecessary string and updates the docs to ensure it's clear that the filter string is just the logic string, not the extra "filter" word at the front.
This resolves #162
* Remove additional "filter" word in default filter value
* Update docstrings for clarity
* Manual testing ensures APRS-IS filtering is working correctly
* Manual testing ensures new output appears in `--help` flag to CLI
=> Resolve double "filter" in default filtering

README.md, src/APRSsharp/Mode.cs, src/APRSsharp/Program.cs
Enables use of serial connection to communicate with a KISS TNC. This is only changes in the CLI app using existing code.
* Adds new `SERIAL_TNC` mode to CLI
* Adds `serialPort` and requires it for that mode
* Refactors the `Mode` enum out of Program.cs
* Refactors out TNC communication logic to be shared across both TCP and serial modes
* Calls out serial access requirements for Linux in readme
* Manually tested new serial TNC mode on both send and receive
* Manually ensured TCP TNC mode still works
* Manually ensured APRS IS mode still works
=> Add Serial TNC to CLI

.editorconfig, Directory.Build.props, src/APRSsharp/Mode.cs, src/APRSsharp/Program.cs, src/AprsParser/AprsParser.csproj, src/KissTnc/KissTnc.csproj, test/AprsIsClientUnitTests/AprsIsClientUnitTests.csproj, test/AprsIsClientUnitTests/ReceiveUnitTests.cs, test/AprsIsClientUnitTests/TimedTests.cs, test/AprsParserUnitTests/AprsParserUnitTests.csproj, test/AprsParserUnitTests/InfoField/MaidenheadBeaconInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/PositionInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/StatusInfoUnitTests.cs, test/AprsParserUnitTests/InfoField/WeatherInfoUnitTests.cs, test/AprsParserUnitTests/PacketAx25UnitTests.cs, test/KissTncUnitTests/KissTncUnitTests.csproj
FxCop is deprecated in favor of .NET Analyzers, [as per Microsoft](https://learn.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers?view=vs-2022).
This PR removes FxCop packages and enables .NET Analyzers across the board.
It also fixes any warnings from the new analyzers.
This resolves #27.
* Removes FxCop packages
* Enables .NET Analyzers across the board
* Adds `.editorconfig` for some larger analysis configs
* Fixes warnings from new analyzers
* New analyzers raised a bunch of new warnings
* Build and tests are now clean on my machine
* Ensured warnings are treated as error in release build (i.e. `dotnet build -c Release` )
=> Switch from FxCop to .NET Analyzers

README.md
#163 changed this repo to a .NET8.0 build target, but missed updating the note on this in the readme.
* Updates the readme to accurately say .NET8.0 for developers.
* Markdown shows valid in my IDE
* Linting will happen in this PR
=> Update readme for .NET 8.0.

src/APRSsharp/Program.cs, src/AprsIsClient/AprsIsClient.cs, test/AprsIsClientUnitTests/AprsIsClientUnitTests.cs, test/AprsIsClientUnitTests/DisposeUnitTests.cs, test/AprsIsClientUnitTests/ReceiveUnitTests.cs
This PR moves from using `ILogger` to log issues internally in the class to creating an event so that client code can act on them. Another major benefit of this approach is eliminating required parameters to the constructor, which makes it even easier to get started.
1. Moves APRS-IS decode failures to report via an event rather than internal logging
2. Removes the required log constructor argument to create an empty constructor
3. Sets up a new test for these things
4. Updates server name parsing logic to be more accurate to servers
* New test passes
* All existing tests pass
=> AprsIsClient Reports Errors Instead of Logs

src/APRSsharp/Program.cs
After #174 , verbose printout was disabled. This switches to a new parameter and method of printing failures. It does that by introducing `--display-parse-failures` flag on the CLI and hooking up to the new event logic from #174.
This removes `--verbosity` and `-v` flags.
* Remove `--verbosity` and `-v` flags from CLI
* Add `--display-parse-failures` flag to CLI for similar functionality
* Hook up `--display-parse-failures` logic to new event-driven exception flow in `AprsIsClient`
* Builds and runs on local machine
=> Display Parse Failures

src/AprsIsClient/AprsIsClient.csproj
Removes a package reference that is unnecessary after the work in #174 but was missed in that PR.
* Build is successful
=> Remove Unnecessary Package Reference from AprsIsClient

src/AprsParser/Position.cs, src/AprsParser/RegexStrings.cs
#179 introduced a few minor static analysis violations. This is okay, because it also brought great functionality. :) Not worth going through another round of PR for minor fixes, and this is easier than playing branch shenanigans.
* Fixes for the linter
* Build passes clean on my machine, we'll see it in the CI as well
=> Build Fixes

src/APRSsharp/Program.cs, src/KissTnc/TcpTnc.cs
The `TcpConnection` object exists to allow easy testing. However, it isn't super useful for users of the package..and requires extra code and understanding extra concepts. This PR adds the ability of `TcpTnc` to manage its own `TcpConnection` while preserving the ability to pass in an object for testing.
* Allow `TcpTnc` construction without a `TcpConnection` object (managed inside the `TcpTnc` object directly)
* Update in CLI app to use the simpler constructor
* CI passes
* Manual test against a TCP KISS TNC is functioning well
=> Remove Required TcpConnection Object from TcpTnc
